SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS S
WHERE S.SALES_DATE LIKE '2022-01-%' 
AND S.BOOK_ID = B.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;