-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM (SELECT S.ONLINE_SALE_ID, S.SALES_DATE,
      YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, 
      S.USER_ID, U.GENDER
      FROM USER_INFO AS U, ONLINE_SALE AS S
      WHERE U.USER_ID = S.USER_ID AND U.GENDER IS NOT NULL) AS SUB
GROUP BY YEAR, MONTH, GENDER 
ORDER BY YEAR, MONTH, GENDER;




