-- 코드를 입력하세요
SELECT APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.APNT_CNCL_YN = 'N' 
AND DATE_FORMAT(A.APNT_YMD,'%Y-%m-%d') ='2022-04-13' AND A.MCDP_CD ='CS'
AND A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD;

