-- 코드를 입력하세요
WITH RECURSIVE RC AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM RC
    WHERE HOUR < 23
)

SELECT RC.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM RC LEFT JOIN ANIMAL_OUTS ON RC.HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR;



